### ISSUE TITLE
The output of blank picture of phonon dispersion

### ISSUE THREAD

**Issue by Bowen-677** [abelcarreras/DynaPhoPy#13]
Dear Abel Carreras:

I have tried to repeat your example to calculate the renormalized phonon dispersion but there are some bugs I can't solve. The output picture is blank as follows and all the commands are input as your README file. I also use the Si to test, the same blank picture is got too. Could you please help me solve this problem? 

![disperse](https://user-images.githubusercontent.com/80866171/128156635-3d9f89c3-cf5f-4c48-9091-c8a21c08853c.png)

**Comment by Bowen-677** [comment]
This problem happens when I use the command "dynaphopy input_gan gan_2000_test.lammpstrj -ts 0.001 --normalize_dos -i".  I choose the 6 Renormalized phonon dispersion and then chose the Renormalized phonon dispersions and linewidths (fat bands)  . Then I got the blank picture



[log.txt](https://github.com/abelcarreras/DynaPhoPy/files/6930217/log.txt)

**Comment by abelcarreras** [comment]
Just a question, are you using the latest version of matplotlib?

**Comment by Bowen-677** [comment]
> Just a question, are you using the latest version of matplotlib?

Yes, the matplotlib is the lastest version(3.4.2) and the DOS picture can got from this script.

**Comment by Bowen-677** [comment]
> > Just a question, are you using the latest version of matplotlib?
> 
> Yes, the matplotlib is the lastest version(3.4.2) and the DOS picture can got from this script.

python version 3.7

**Comment by Bowen-677** [comment]
> OK, thank you for your feedback.
> I just updated dynaphopy (v1.17.9) in master branch with hopefully the fix for the issue.
> It should show up very soon in pypi and conda.

Thank you very much and it works well now !!!
