### ISSUE TITLE
4 - Frequency vs linewidth (interpolated mesh)

### ISSUE THREAD

**Issue by Bowen-677** [abelcarreras/DynaPhoPy#14]
Dear Abel carreras:

We need to calculate the spectral function of the material to give the information of different components. Can we solve this problem with your software? Additionally, the picture as follows is the 4 - Frequency vs linewidth (interpolated mesh) of GaN. Can you please explain what the different colors represent? 

![frequency vs linewidth](https://user-images.githubusercontent.com/80866171/129668015-22e1e27f-b32e-48f1-865c-aea30da3fe3e.png)

**Comment by abelcarreras** [comment]
Dear @Bowen-677,

Sorry, I am not familiar with spectral function of the material, maybe if you provide me more details I can help.
Regarding to Frequency vs linewidth plot, the colors correspond to the different phonon branches.

**Comment by Bowen-677** [comment]
> Dear @Bowen-677,
> 
> Sorry, I am not familiar with spectral function of the material, maybe if you provide me more details I can help.
> Regarding to Frequency vs linewidth plot, the colors correspond to the different phonon branches.

Dear Abel carreras:

  Thanks for your reply, your code really help me a lot. I still want to ask how to save the output data of the process. I'm trying to get the output data by modifying the code, but it still got only the picture. I really hope I can get the data of the phonon dispersion and DOS. 

Bowen

**Comment by abelcarreras** [comment]
If you are interested in the band structure and DOS the best way is to store the renormalized force constants and use phonopy with option  **-readfc** option.

**Comment by Bowen-677** [comment]
> If you are interested in the band structure and DOS the best way is to store the renormalized force constants and use phonopy with option **-readfc** option.

Sorry, I did not make myself clear.
I want to get these calculated data by DynaPhoPy. Because I still need the data to do some changes, such as change the verticle unit from THz to cm-1

**Comment by abelcarreras** [comment]
Ah, Ok you mean using dynaphopy's API?

**Comment by Bowen-677** [comment]
> Ah, Ok you mean using dynaphopy's API?

Yes, but I can't use it. I didn't see it in the manual either.

**Comment by yxf0125** [comment]
> Ah, Ok you mean using dynaphopy's API?

Dear abelcarreras,

I have the same problem.  Thus, I modified part of the DP source code:

I commented out the codes for "**plt**" and added the codes for "**save**".

Unfortunately, I do not get some calculated date by DynaPhoPy. Could you help me? 
Thanks!

Best regard，
Xuefei Yan

**Comment by abelcarreras** [comment]
Sure,

Here you have a small sniped to do the trick

```python
import dynaphopy.interface.phonopy_link as pho_interface

quasiparticle = dynaphopy.Quasiparticle(trajectory)

renormalized_force_constants = quasiparticle.get_renormalized_force_constants()

phonopy_dos = pho_interface.obtain_phonopy_dos(quasiparticle.dynamic.structure,
                                               mesh=quasiparticle.parameters.mesh_phonopy,
                                               projected_on_atom=quasiparticle.parameters.project_on_atom,
                                               NAC=quasiparticle.parameters.use_NAC,
                                               force_constants=renormalized_force_constants)

print(phonopy_dos)

bands_and_labels = quasiparticle.get_band_ranges_and_labels()

renormalized_bands = pho_interface.obtain_phonon_dispersion_bands(quasiparticle.dynamic.structure,
                                                                  bands_and_labels['ranges'],
                                                                  force_constants=renormalized_force_constants,
                                                                  NAC=quasiparticle.parameters.use_NAC,
                                                                  band_connection=False,
                                                                  band_resolution=quasiparticle.parameters.band_resolution)

print(renormalized_bands)

```
You can get the harmonic version by omitting "force_constants" option.

**Comment by yxf0125** [comment]
> Sure,
> 
> Here you have a small sniped to do the trick
> 
> ```python
> import dynaphopy.interface.phonopy_link as pho_interface
> 
> quasiparticle = dynaphopy.Quasiparticle(trajectory)
> 
> renormalized_force_constants = quasiparticle.get_renormalized_force_constants()
> 
> phonopy_dos = pho_interface.obtain_phonopy_dos(quasiparticle.dynamic.structure,
>                                                mesh=quasiparticle.parameters.mesh_phonopy,
>                                                projected_on_atom=quasiparticle.parameters.project_on_atom,
>                                                NAC=quasiparticle.parameters.use_NAC,
>                                                force_constants=renormalized_force_constants)
> 
> print(phonopy_dos)
> 
> bands_and_labels = quasiparticle.get_band_ranges_and_labels()
> 
> renormalized_bands = pho_interface.obtain_phonon_dispersion_bands(quasiparticle.dynamic.structure,
>                                                                   bands_and_labels['ranges'],
>                                                                   force_constants=renormalized_force_constants,
>                                                                   NAC=quasiparticle.parameters.use_NAC,
>                                                                   band_connection=False,
>                                                                   band_resolution=quasiparticle.parameters.band_resolution)
> 
> print(renormalized_bands)
> ```
> 
> You can get the harmonic version by omitting "force_constants" option.

Thanks, I got it.

**Comment by abelcarreras** [comment]
Of cours you can substitute most of the parameters I set from standard parameters class in dynaphopy by explicit values
