### ISSUE TITLE
Error occurred when running GaN_lammps in examples.

### ISSUE THREAD

**Issue by ZhangMin-qq** [abelcarreras/DynaPhoPy#18]
Hi, I'm sorry to bother you. I just started using dynaphopy, and I got the following error when running GaN _ lammps in the examples directory. What may have caused this mistake? How should I avoid such errors? The following is my error report record. Thank you for your help.
[slurm-749533.txt](https://github.com/abelcarreras/DynaPhoPy/files/9969784/slurm-749533.txt)

![error](https://user-images.githubusercontent.com/117817422/200802837-f730f8a4-411d-4e02-8ed2-6be8f300be90.JPG)

**Comment by abelcarreras** [comment]
Hi, this is a compatibility issue with recent versions of phonopy that was solved in v1.17.1.

https://github.com/abelcarreras/DynaPhoPy/commit/3667d169867fd1c6fbe7f78e1df6bfbcffd4f566

I think that updating dynaphopy will solve your issue.

**Comment by ZhangMin-qq** [comment]
> Hi, this is a compatibility issue with recent versions of phonopy that was solved in v1.17.1.
> 
> [3667d16](https://github.com/abelcarreras/DynaPhoPy/commit/3667d169867fd1c6fbe7f78e1df6bfbcffd4f566)
> 
> I think that updating dynaphopy will solve your issue.


Thank you for your advice! The problem has been solved with your help.
