### ISSUE TITLE
Maxwell-Boltzmann distribution analysis does not fit well

### ISSUE THREAD

**Issue by wenlibin02** [abelcarreras/DynaPhoPy#2]
Dear Abel Carreras, 

I installed the dynaphopy package and tested the Si example you gave in the doc. VASP was used for the testing, with 1E4 MD steps at 800 K. Then I ran the dynaphopy script in interactive mode, using the OUTCAR produced by VASP calculation. The Maxwell-Boltzmann distribution analysis plotted a graph and printed a fitting temperature (2022.4 K), but I found the fitting curve deviated too much from the data, as shown below. 
![pipefile](https://user-images.githubusercontent.com/4525430/28463512-53298c2e-6e53-11e7-9d18-2e9f7f582f5a.png)

I tried to change the number of MD steps used for analysis by specifying ``-n`` parameter, i.e. ``-n 8000`` or ``-n 5000``, resulting in exactly the same fitting results. It seems it did not really fit the data at all. 

More Information on my setup:
1) dynaphopy: install using pip today (2017 07 21)
2) Debian system, with updated numpy and scipy packages

**Comment by abelcarreras** [comment]
That's strange. How many atoms did you use in the supercell?
Have you tried reading the XDATCAR instead? (remember to set the time step using -ts flag)
What do you obtain for the atomic displacements distribution calculation?

**Comment by wenlibin02** [comment]
@abelcarreras I used nearly the same configuration as the Si example in the doc of DynaPhoPy. I just tested using the XDATCAR, and found the velocity fitted well. Then I tried using different number of steps: ``-n 5000`` and ``-n 2000`, giving slightly different temperatures fluctuating around 800 K. That means XDATCAR gave the correct results for Maxwell-Boltzmann distribution fitting. The same tests using OUTCAR always give 2022.4 K, no matter how many MD steps I specified. 

Except the difference in Maxwell-Boltzmann distribution analysis, 
* the renormalized phonon dispersion looks the same in the two cases
* "Peak analysis" at Gamma point using ``-n 8000`` gives the following results, 
![pipefile](https://user-images.githubusercontent.com/4525430/28487926-1a0e60cc-6ed0-11e7-88bf-85b4902951ca.png)
* "Atomic Displacement" analysis at direction (1,0,0) gives, 
![pipefile](https://user-images.githubusercontent.com/4525430/28487967-9489ee42-6ed1-11e7-9bf0-62878385de8c.png)

I used VASP 5.3.3 for the MD calculation.

**Comment by abelcarreras** [comment]
Ok, I see. I will check the OUTCAR parser. I use a slightly different version of VASP so maybe something changed in the OUTCAR file. The differences may also be due to the precision. The XDATCAR has more precision than the OUTCAR. I recommend to read the trajectory always from the XDATCAR file. In the future I plan to drop the OUTCAR parser support.
Thanks a lot for the feedback I will revise the OUTCAR parser and the online manual.

**Comment by wenlibin02** [comment]
Thank you for your reply. Your code is really nice.
