### ISSUE TITLE
Setup.py fails on Mac because erroneously detecting Windows

### ISSUE THREAD

**Issue by mcallsen** [abelcarreras/DynaPhoPy#21]
In the requirements line in setup.py there is a check whether the platform is windows:

`install_requires=['phonopy', 'numpy', 'scipy', 'matplotlib'] + ["windows-curses"] if "win" in sys.platform else [],`

On MacOS `sys.platform = 'darwin'` which also contains `win` as a substring and therefore `"windows-curses"` is required. 

A safer check would be `if sys.platform in ["win32", "cygwin"]` which are the two possible options for Windows I found in the documentation of `sys.platform`.

**Comment by abelcarreras** [comment]
HI @mcallsen you are absolutely right, I will fix it.
Thank you for reporting this bug

**Comment by abelcarreras** [comment]
Done
