### ISSUE TITLE
Can you tag on github when pip releases a new version？

### ISSUE THREAD

**Issue by yuhldr** [abelcarreras/DynaPhoPy#24]
Since 1.17.0, there is no tag tag on GitHub, Can you tag on github when pip releases a new version？

When I package for ArchLinux on Aur: [python-dynaphopy](https://aur.archlinux.org/packages/python-dynaphopy), I can't get the latest source code, currently only on pip, pip's download connection is not fixed, it is very inconvenient when packing

**Comment by abelcarreras** [comment]
Ok, sorry for the inconvenience. 
I will tag new versions from now on.
