### ISSUE TITLE
Question on Installation

### ISSUE THREAD

**Issue by LePingKYXK** [abelcarreras/DynaPhoPy#25]
Hi Abel,
I found the link to the Anaconda-supported installation of `DynaPhoPy` https://anaconda.org/conda-forge/dynaphopy. It provides an alternate way `conda install -c conda-forge dynaphopy` to install DynaPhonPy,

However, neither the [GitHub](https://github.com/abelcarreras/DynaPhoPy#installation-instructions) nor the [DynaPhoPy](http://abelcarreras.github.io/DynaPhoPy/index.html#top) website mentioned via `conda install` method. 

The ways that I have seen are
`pip install dynaphopy --user` or `python setup.py install --user` from [GitHub](https://github.com/abelcarreras/DynaPhoPy#installation-instructions), 
`python setup.py install --user` or `python setup_openmp.py install --user` from [DynaPhoPy](http://abelcarreras.github.io/DynaPhoPy/index.html#top).

I was wondering if the `conda install` method is recommended and who maintains it.

Best regards,
Huan

**Comment by abelcarreras** [comment]
Hi Huan,

Unfortunately, I don't know who is the maintainer of dynaphopy's conda package.
I'm currently maintaining only gitHub and pypi repositories.

**Comment by abelcarreras** [comment]
In modern platforms I think you don't need even  **--user** option anymore. This was introduced in case you didn't have administrator rights, so the package will be installed under the user home dir. I think now this is done automatically by **pip**.

Regarding  requirements.txt you can just install them with **pip**:

_pip install -r requirements.txt_

You don't need to comment anything.

Anyway, if you just want to install dynaphopy I would recommend to just install it from PyPi repository (this is the easiest way):

_pip install dynaphopy_

This should work even inside a conda environment.

**Comment by abelcarreras** [comment]
If these scripts are not included in the installation then you can place them in any location that is included in your $PATH environment variable for convenience (e.g. /usr/bin/, /usr/local/bin, etc.)

**Comment by LePingKYXK** [comment]
> If these scripts are not included in the installation then you can place them in any location that is included in your $PATH environment variable for convenience (e.g. /usr/bin/, /usr/local/bin, etc.)

Thanks a lot for your help.
