### ISSUE TITLE
size is increased, after trajectory in the format of lammps is transfered to the format of hdf5

### ISSUE THREAD

**Issue by XIANG-Xing** [abelcarreras/DynaPhoPy#26]
Hi,

When I change the format of trajectory from lammpstrj to hdf5, the size is increased from 13.5 MB to 53.1 MB. It is quite wired because the file in hdf5 is expected to be smaller. Could you give me some helps?

The command for trajectory production is:
dump            dynaphopy_pos all custom 100 LiSi_${t}_pos.lammpstrj x y z
dump_modify     dynaphopy_pos sort id

The format transfer is conducted following:
dynaphopy input LiSi_300_pos.lammpstrj -ts 0.001 -sv LiSi_300_pos.hdf5

**Comment by abelcarreras** [comment]
Hi,

**-sv** tag  saves additional data aside from the trajectory (including lattice info, velocity and projected velocities).
If you want to reduce the file size I recommend to use **--velocity-only** tag to save only the velocity or use **--save_vc_hdf5** to save only the velocity projected onto a wave vector.

**Comment by abelcarreras** [comment]
Hi,

**-sv** tag  saves additional data aside from the trajectory (including lattice info, velocity and projected velocities).
If you want to reduce the file size I recommend to use **--velocity-only** tag to save only the velocity or use **--save_vc_hdf5** to save only the velocity projected onto a wave vector.

**Comment by XiangXing96** [comment]
Ok. Thank you very much.
