### ISSUE TITLE
option to modify symprec=1e-5 for force constant symmetrization

### ISSUE THREAD

**Issue by bobleesj** [abelcarreras/DynaPhoPy#28]
Hi Abel,

I noticed that I had to adjust the symmetry tolerance from 1e-5 to 1e-2 to ensure that Phonopy recognized the space group correctly for my system.

I am also hoping to try out force constant symmetrization using DynaPhoPy. I have noticed that the `symprec` parameter has a default value of 1e-5 when flag `--fcsymm` is used. Is there a way to easily modify `symprec`?

Best,
Bob

**Comment by abelcarreras** [comment]
Hi Bob, at this moment there is no way to change this option from the command line interface of python API. I will include this option in the next version.
Meanwhile the only way to change this parameter is by modifying the code.
Here:
https://github.com/abelcarreras/DynaPhoPy/blob/592efebab22792ca47f680934a8407321083d6f5/dynaphopy/interface/phonopy_link.py#L82

**Comment by bobleesj** [comment]
Thanks!
