### ISSUE TITLE
Whether the dynaphopy can be applied to calculate the phonon lifetime vs frequency?

### ISSUE THREAD

**Issue by Guancred** [abelcarreras/DynaPhoPy#29]
Hi,
I want to confirm whether the dynaphopy can be applied to calculate the phonon lifetime vs frequency as attached figure? 

Thanks,

![image](https://github.com/abelcarreras/DynaPhoPy/assets/91767936/34bfe7f6-e68b-4ece-b457-892c45c8a1ca)

**Comment by abelcarreras** [comment]
Yes, dynaphopy can calculate phonon linewidths which are the inverse of lifetimes

**Comment by Guancred** [comment]
> Yes, dynaphopy can calculate phonon linewidths which are the inverse of lifetimes

I found it when i conducted the following steps:
1) dynaphopy -i input XDATCAR
2) selecting 6 (Renormalized phonon dispersion)
3) Then, select 4 (Frequency vs linewidth)

Then, some information will show in the screen as the following figure. For my case, for every Q-point, there are 40 peaks during the frequency, so if i want to plot the linewidth vs. frequency, how to collect the data? whether the data can be output with the txt style?

Thanks very much
![image](https://github.com/abelcarreras/DynaPhoPy/assets/91767936/41753737-8007-4426-ba05-52423354618e)
