### ISSUE TITLE
Output renormalized FORCE_SETS

### ISSUE THREAD

**Issue by chejunwei2** [abelcarreras/DynaPhoPy#30]
Dear developer, 
I want to get the renormalized FORCE_SETS from the Dynaphopy package. But I found that the IFCs I get are in FORCE_CONSTANTS format. So I would like to know if Dynaphopy can output IFCs in FORCE_SETS format. Or if it can convert FORCE_CONSTANTS to FORCE_SETS.
Best regards,
junwei

**Comment by abelcarreras** [comment]
HI @chejunwei2 , dynaphopy currently does not have this feature. However the force constants format is identical to the one used by phonopy. Have you check if phonopy implements this option?

**Comment by chejunwei2** [comment]
Thanks very much for you reply.  I have checked, and phonopy can convert  FORCE_SETS to FORCE_CONSTANTS, but the reverse doesn't work.
