### ISSUE TITLE
The program shows an error！

### ISSUE THREAD

**Issue by Liang1Kai** [abelcarreras/DynaPhoPy#31]
Hi developer,
I have prepared all the necessary documents, input, force contants, XDATCAR, POSCAR. 
But  after the program is run, it is displayed: **No force contants available.** And there is no data output.
What's the problem, please!
Looking forward to your reply！Thanks so much！
 Liang Kai

**Comment by Liang1Kai** [comment]
thanks for your reply，it's sure that the force constants file got from the phonopy.  I tried again. But it still error.I will check the manual and examples for more details.And try. Thanks again.



---- Replied Message ----
| From | Abel ***@***.***> |
| Date | 04/13/2024 03:56 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [abelcarreras/DynaPhoPy] The program shows an error！ (Issue #31) |

Dear @Liang1Kai,

in order to perform a dynaphopy calculation you need to include a force constants file and specify it in dynaphopy's input file. This force constants file has to be in phonopy format. You can use phonopy to get this file.
Check the manual and examples for more details.

**Comment by abelcarreras** [comment]
Sorry, I modified the comment later on. I think it may be a typo in the input file so the force constants keyword is not recognized. That's why I advised you to check the examples to make sure that the syntax is correct. Also you can try to run the provided examples to make sure that your installation works properly

**Comment by Liang1Kai** [comment]
OK！i will to try.Thanks so much.



---- Replied Message ----
| From | Abel ***@***.***> |
| Date | 04/13/2024 21:06 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [abelcarreras/DynaPhoPy] The program shows an error！ (Issue #31) |

Sorry, I modified the comment later on. I think it may be a typo in the input file so the force constants keyword is not recognized. That's why I advised you to check the examples to make sure that the syntax is correct. Also you can try to run the provided examples to make sure that your installation works properly
