### ISSUE TITLE
The error when run the dynaphopy

### ISSUE THREAD

**Issue by ZengZezhu** [abelcarreras/DynaPhoPy#8]
Dear dynaphopy team,

sorry to bother you with this issue. I try to run the dynaphopy to obtain the phonon frequency and linewidths. However, when I run the command like below:

dynaphopy input_file XDATCAR -ts 0.02  -sdata

there is a confused bug:
Reading VASP POSCAR structure
Reading XDATCAR file
This could take long, please wait..
No velocity provided! calculating it from coordinates...
MD cell size relation: [2 2 2]
Using 20000 steps
Traceback (most recent call last):
  File "/home/zeng/.local/bin/dynaphopy", line 4, in <module>
    __import__('pkg_resources').run_script('dynaphopy==1.16.6', 'dynaphopy')
  File "/home/zeng/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/zeng/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/zeng/.local/lib/python2.7/site-packages/dynaphopy-1.16.6-py2.7-linux-x86_64.egg/EGG-INFO/scripts/dynaphopy", line 362, in <module>
    
  File "build/bdist.linux-x86_64/egg/dynaphopy/__init__.py", line 1196, in write_quasiparticles_data
  File "build/bdist.linux-x86_64/egg/dynaphopy/__init__.py", line 1086, in get_commensurate_points_data
  File "build/bdist.linux-x86_64/egg/dynaphopy/interface/phonopy_link.py", line 155, in obtain_phonopy_dos
  File "build/bdist.linux-x86_64/egg/dynaphopy/interface/phonopy_link.py", line 79, in get_phonon
  File "build/bdist.linux-x86_64/egg/dynaphopy/atoms.py", line 97, in get_supercell_phonon
  File "build/bdist.linux-x86_64/egg/dynaphopy/atoms.py", line 187, in get_force_sets
TypeError: 'NoneType' object has no attribute '__getitem__'

I try to obtain the temperature profile and it is worked. I also test the examples and worked very well. 
Could you give me some advice about this problem?

**Comment by abelcarreras** [comment]
Something wrong with the force constants.
Can you post the input_file you are using?

**Comment by ZengZezhu** [comment]
thank you for your information! I just change the set of FORCE_SETS and now its worked.
By the way, when I used the XDATCAR that the coordinates are write by Cartesian format to run the dynaphopy, there is a error: 
Trajectory file format not recognized
while the direct format is ok.
Is it the limit of dynaphopy?

**Comment by ZengZezhu** [comment]
and I have some puzzles to the unitcell of dynaphopy. Can I use the primitive cell as unitcell in the input_file? because I don't want to enlarge the unitcell (to run the MD) by integer times.

**Comment by abelcarreras** [comment]
XDATCAR in Cartesian is not currently supported, sorry.
Regarding the use of the primitive cell as unitcell, in principle no problem. 
You can define primitive matrix as identity matrix. That means that 
the primitive cell will be equal to the unitcell, which in your case you can define 
as your primitive cell.

**Comment by ZengZezhu** [comment]
Thank you for your information!

This is my input_file:

STRUCTURE FILE POSCAR
POSCAR

FORCE CONSTANTS
FORCE_CONSTANTS

PRIMITIVE MATRIX
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0

SUPERCELL MATRIX PHONOPY
0 5 5
5 0 5
5 5 0

I used the primitive cell as unitcell. But there is a error: 
Reading VASP POSCAR structure
Reading old style POSCAR
Reading XDATCAR file
This could take long, please wait..
No velocity provided! calculating it from coordinates...
0.0679491926422
Warning! Defined unit cell and MD supercell do not match!
Cell size relation is not integer: [ 5.77350269  5.77350269  5.77350269]

Could you give me some advice?

**Comment by abelcarreras** [comment]
Supercell (the one used in your MD simulation) should be a multiple of your unit cell (defined in dynaphopy input). That seems not to be the case according to the error message. In the error it says that the relation between supercell and unitcell is not integer so it is not multiple.
The supercell used in the MD is detected automatically from the unit cell. 

Also SUPERCELL MATRIX PHONOPY should be diagonal and integer. This defines the force constants supercell matrix that you have used to calculate the force constants in phonopy.
The unit cell defined in dynaphopy should be the same as the one used to calculate the force constants in phonopy.

You can check the input details in dynaphopy manual here:
http://abelcarreras.github.io/DynaPhoPy/usage.html

**Comment by ZengZezhu** [comment]
Thank you so much for your comments!

Best,
